# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planoleituras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetas',
            name='etiqueta',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
