# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planoleituras', '0002_auto_20170325_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetas',
            name='tipo_etiqueta',
            field=models.CharField(choices=[('CTW', 'Content Words'), ('COW', 'Commom Words')], default='COW', max_length=4),
        ),
    ]
