# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planoleituras', '0003_etiquetas_tipo_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=50)),
                ('correto', models.BooleanField(default=True)),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planoleituras.Etiquetas')),
            ],
            options={
                'verbose_name': 'Palavra Etiqueta',
                'verbose_name_plural': 'Palavras Etiquetadas',
            },
        ),
        migrations.CreateModel(
            name='Textos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('texto', models.TextField(verbose_name='Texto completo')),
                ('origem', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Texto',
                'verbose_name_plural': 'Textos',
            },
        ),
        migrations.AddField(
            model_name='dicionario',
            name='texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planoleituras.Textos'),
        ),
    ]
