# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planoleituras', '0005_auto_20170410_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicionario',
            name='sentenca',
            field=models.IntegerField(default=0),
        ),
    ]
