# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planoleituras', '0006_dicionario_sentenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetas',
            name='tipo_etiqueta',
            field=models.CharField(choices=[('CTW', 'Palavras de Conteúdo'), ('COW', 'Palavras Comuns'), ('MSE', 'Marcador de Sentença'), ('IGN', 'Ignoradas')], default='COW', max_length=4),
        ),
    ]
