# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planoleituras', '0007_auto_20170410_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentencas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('itens', models.CharField(max_length=250)),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planoleituras.Textos')),
            ],
            options={
                'verbose_name': 'Sentença',
                'verbose_name_plural': 'Sentenças',
            },
        ),
        migrations.RemoveField(
            model_name='dicionario',
            name='sentenca',
        ),
    ]
