# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentdesc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributos',
            name='tipo',
            field=models.CharField(choices=[('TXT', 'Texto'), ('NBR', 'Número'), ('LTXT', 'Texto Grande'), ('DT', 'Data')], default='TXT', max_length=4),
        ),
    ]
