# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentdesc', '0003_auto_20170221_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributos',
            options={'verbose_name': 'Atributo', 'verbose_name_plural': 'Atributos'},
        ),
        migrations.AlterModelOptions(
            name='atributos_habilidades',
            options={'verbose_name': 'Atributos / Habilidades', 'verbose_name_plural': 'Atributos / Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='elementos_texto',
            options={'verbose_name': 'Elemento do Texto', 'verbose_name_plural': 'Elementos do Texto'},
        ),
        migrations.AlterModelOptions(
            name='habilidades_leitura',
            options={'verbose_name': 'Habilidade de Leitura', 'verbose_name_plural': 'Habilidades de Leitura'},
        ),
    ]
